# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='sytle',
            new_name='style',
        ),
    ]
